// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmprestimoLivros.API.Models
{
    public partial class Livro
    {
        public Livro()
        {
            LivroClienteEmprestimo = new HashSet<LivroClienteEmprestimo>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nomeLivro")]
        [StringLength(50)]
        [Unicode(false)]
        public string NomeLivro { get; set; }
        [Required]
        [Column("autor")]
        [StringLength(100)]
        [Unicode(false)]
        public string Autor { get; set; }
        [Required]
        [Column("editora")]
        [StringLength(50)]
        [Unicode(false)]
        public string Editora { get; set; }
        [Required]
        [Column("anoPublicacao")]
        [StringLength(10)]
        [Unicode(false)]
        public string AnoPublicacao { get; set; }
        [Required]
        [Column("edicao")]
        [StringLength(10)]
        [Unicode(false)]
        public string Edicao { get; set; }

        [InverseProperty("IdLivroNavigation")]
        public virtual ICollection<LivroClienteEmprestimo> LivroClienteEmprestimo { get; set; }
    }
}